name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target-wheel: manylinux1_x86_64.whl
          - os: ubuntu-latest
            target-wheel: manylinux_2_17_aarch64.manylinux2014_aarch64.whl
          - os: windows-latest
            target-wheel: win_amd64.whl
          - os: windows-latest
            target-wheel: win_arm64.whl

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install build wheel
      - name: Build wheel
        env:
          PLAYWRIGHT_firefox_TARGET_WHEEL: ${{ matrix.target-wheel }}
        run: python setup.py bdist_wheel

      - name: Upload built wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.target-wheel }}
          path: dist/*.whl

  # 只用linux amd64上传 PyPI
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build-wheels
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          merge-multiple: true
          path: dist
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install twine
        run: python -m pip install twine
      - name: Publish to PyPI
        run: python -m twine upload dist/*.whl --non-interactive -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
